### PR TITLE
OHLCV Rest Methods

### PR DESCRIPTION
**Pull request by byblakeorriver**
Adds the OHLCV methods to the project. There are alternate "latest_data" and "historical_data" functions that could be written, but I just added the ones  that I noticed they had in the java SDK.

### CODE REVIEW

**Comment by byblakeorriver** [comment]
Still need to do some more testing.

**Comment by soerenmartius** [comment]
Hi @byblakeorriver,

Thanks a lot for contributing to this project. I have not been able to continue working on this recently since I've changed jobs. Would you be interested in maintaining this project with me? Happy to share ownership.

The PR looks good btw. Let me know if and when you'd like to get this merged.

**Comment by byblakeorriver** [comment]
Hi @soerenmartius,

I would be happy to be a maintainer! 
I still need to do some testing, but once it is done I will let you know, and we can get this merged.
Thanks for getting back to me!

**Comment by soerenmartius** [comment]
> Hi @soerenmartius,
> 
> I would be happy to be a maintainer!
> I still need to do some testing, but once it is done I will let you know, and we can get this merged.
> Thanks for getting back to me!

Perfect! Thanks for the heads-up! I am gonna add you as a maintainer to this project in a minute and will update the README.md also.

**Comment by soerenmartius** [comment]
> > Hi @soerenmartius,
> > I would be happy to be a maintainer!
> > I still need to do some testing, but once it is done I will let you know, and we can get this merged.
> > Thanks for getting back to me!
> 
> Perfect! Thanks for the heads-up! I am gonna add you as a maintainer to this project in a minute and will update the README.md also.

@byblakeorriver you should have received an invite

**Comment by byblakeorriver** [comment]
Thanks @soerenmartius! This is my official first open source maintainer assignment! Cheers! :beers:

**Comment by byblakeorriver** [comment]
@soerenmartius Think this one is ready to go!

**Pull request merged**
